- name: My first play
  hosts: myhosts
  become: yes
  tasks:
  - name: Ping my hosts
    ansible.builtin.ping:

  - name: Print message
    ansible.builtin.debug:
      msg: Hello world

  - name: Update all packages to their latest version
    ansible.builtin.apt:
      name: "*"
      state: latest